/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Draw: typeof import('./src/components/Draw.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MaintenanceDialog: typeof import('./src/components/MaintenanceDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanList: typeof import('vant/es')['List']
    VanPopover: typeof import('vant/es')['Popover']
  }
}
