const en = {
  "loading": "Processing...",
  "net": "Network",
  "amount": "Amount",
  "Available": "Available",
  "Trans-Fee": "Withdrawal Fee",
  "withdrawal-scuu": "Withdrawal \n succeeded",
  "AddressFormatError": "Address Error",
  "tip": "Confirmation",
  "CurrentHoldings": "Current Holdings",
  "TotalHoldings": "Total Holdings",
  "Exit": "Exit",
  "Amount": "Amount",
  "Ok": "Yes I know",
  "OK1": "Confirm",
  "Confirm":"Confirm",
  "DodeleteDode": "Do you want to delete this super node ?",
  "deleteSucc": "Delete Successfully",
  "superList": 'Super Node List',
  "SuperNode": "Super Node",
  "SuperSettings": "Super Node Settings",
  "Rewardratio": "Reward Ratio",
  "Settings": "Settings",
  "StakeTime": "Staking Period",
  "ConnectBNBChain": "Connect With BNB Chain",
  "pricerepledge": "The price has been updated, please re pledge",
  "SettingsFull": "Set Successfully",
  "InviteWallAddre": "Invitation Wallet Address",
  "EnterInviteWallAddre": "Please Enter Invitation Wallet Address",
  "ConnectWallet": "Connect Wallet",
  "connectyourwallet": "Please connect your wallet",
  "Balance": "Balance",
  "Withdrawtowallet": "Withdraw To Wallet",
  "Stake": "Stake",
  "Two-Week": "Two-Week",
  "InsufficientBLCbalance": "Insufficient BLC balance",
  "InsufficientFTDbalance": "Insufficient FTD balance",
  "Authorization": "Authorizing...",
  "Authorizationsuccessful": "Authorization Successfully",
  "AuthorizationFail": "Authorization Failed",
  "Three-Week": "Three-Week",
  "Four-Week": "Four-Week",
  "Flexible": "Flexible",
  "CurrentStaking": "Current Staking",
  "StakingInProcess": "Buying In Process",
  "FlexibleStaking": "Flexible Staking",
  "Minted": "Airdropped",
  "StakingPeriod": "Staking Period",
  "ExpiryTime": "Expiry Time",
  "Redeem": "Redeem",
  "Redeeming": "Redeeming...",
  "copied": "Copy Successfully",
  "Restake": "Restake",
  "AuthorizationTo": "Authorization",
  "NoStake": "No Current Stake",
  "Participate": "Referral Program",
  "Users": "Users",
  "Node": "Node",
  "Super": "Super ",
  "NumberUsers": "Invited Users",
  "TotalNodeAmount": "Total Node Staking Amount",
  "SuperTotalNodeAmount": "Total Spuer Node Staking Amount",
  "TotalEarningsFTD": "Total Earnings in FTD",
  "SuperTotalEarningsFTD": "Total Earnings in FTD",
  "InvitationLink": "Invitation Address",
  "Cancel": "Cancel",
  "Copylink": "Copy Address",
  "StakEd": "Expired",
  "NoMore": "No More",
  "surestake": "Are you sure you want to redeem this stake?",
  "RedeemSuccessful": "Redeem Successfully",
  "Two-WeekSuccessful": "Two-Week Staking Successfully",
  "ID": "ID",
  "JoinDot": "Please join the node first",
  "InvitedUsers": "Invited Users",
  "ActiveUsers": "Active Users",
  "WalletAddress": "Wallet Address",
  "RegistrationDate": "Registration Time",
  "NoContent": "No Data",
  "TotalStakingAmount": " Total Staking Amount",
  "NumberofUsers": "Invited Users",
  "TotalFTDMinted": "Super Node Reward",
  "NodeReward": "Node Staking Reward",
  "okchian": "Please select the correct main chain",
  "InvitationAddress": "Inviter Wallet Address",
  "Price": "Price：",
  "Withhold30%": "Withhold 30% of withdrawals as computational power investment",
  "NodeUnlocked": "Node Unlocked",
  "Annualpledge": "Annual pledge",
  "Withdrawalquantity": "Withdrawal Quantity",
  "details": " Details",
  "Mypledge": "My pledge",
  "AtLeast": "At Least ",
  "Withdraw": "Withdraw",
  "TransactionFee": "Transaction Fee:",
  "WithdrawSuccessful": "Withdraw Successful",
  "StakeSuccessful": "Subscription Confirmed",
  "StakeFailed": "Subscription failed",
  "totalStake": "Total Staking Amount",
  "ConfirmingBlock": "Confirming Block",
  "EnterWalletAddress": "Enter Wallet Address",
  "Staking": "Staking",
  "Expired": "Expired",
  "ConfirmingRedemption": "Confirming Redemption",
  "Redeemed": "Redeemed",
  "DataStatistics": "Data statistics as of ",
  "loadig": "loadig...",
  "SystemMaintenance": "The system is under maintenance, please try again later.",
  "desNo3000": "The cumulative total mortgage value cannot exceed 3000 USDT",
  "WithdrawAmount": "Withdraw Quantity",
  "PowerAllocation": "Power Reallocation",
  "pledgeYear": "The staking period is 1 year",
  "areYouOut": "Are you sure you want to log out from ",
  "mei": " ?",
  "SuperAirdrop": "SN Community Airdrop",
  "SuperAirdrop1": "Super Node Community Airdrop",
  "totalSuperAirdrop": "Total Super Node Community Airdrop",
  "NodeAirdrop": "Node Community Airdrop",
  "totalNodeAirdrop": "Total Node Community Airdrop",
  "Quantityreceived": "Quantity Received",
  "WalletBalance": "Wallet Balance: ",
  "APR": "APR ：",
  "released": "Released Balance",
  "airdropped": "Airdropped Balance",
  "burned": "Burned",
  "available": "Available Balance",
  "withdrawable": "Withdrawable Balance",
  "staging_balance": "Available Release Amount",
  "burn_info": "Burn Rate / Release Period / Burn Quantity",
  "release_action": "Release",
  "release_empty": "Release Quantity cannot be empty",
  "burn_pool_balance": "Burn Pool Balance",
  "burn_pool_insufficient": "Insufficient Available Balance in Burn Pool",
  "burn": "Burn Token",
  "pool": "Burn Pool",
  "Burn":"Burn",
  "pending_release": "Pending Released Balance",
  "release_Amount":"Release Quantity",
  "days":"days",
  "sureBurn":"Are you sure you want to burn it?",
  "enterQuantity":"The destruction quantity must be greater than 0",
  "Operationsuccessful":"Operation Successful",
  "Insufficientrelease":"Insufficient balance for installment release",
  "TransactionCancelled":"Transaction Cancelled",
  "All":"All",
  "Insufficien":"Insufficient balance",
  "Insufficientwithdrawal":"Insufficient balance available for withdrawal",
  "Insufficientreleased":"Insufficient released balance",
  "Signatureinprogress":"Signature in progress...",

  "nodeSub":"Node Subscription",
  "nodeSubTitle":"Background Introduction",
  
  "desMain":"CESS is committed to building a blockchain-based decentralized cloud storage system, utilizing advanced virtualization technology to efficiently manage global storage resources. The platform aims to provide consistent and efficient decentralized storage services to users worldwide. Currently, the CESS Pathfinder nodes are available for sale. Out of ",
  "desMain1":" nodes, ",
  "desMain2":"have already been sold, leaving only ",
  "desMain3":" nodes remaining—an opportunity not to be missed.",
  "card1Title":"Industry Leadership",
  "card1Desc":"CESS pioneered the IEEE decentralized storage protocol standard, laying a solid foundation for global applications and driving the industry's standardization process.",
  "card2Title":"Global Market and Government Resources",
  "card2Desc":"CESS is a key member of GBA and BA, leading the GBA Asia chapter, and actively promoting the global adoption and development of decentralized storage.",
  "card3Title":"Policy Advocacy and Industry Dialogue",
  "card3Desc":"CESS was invited to attend the DePIN Fly-In briefing at the U.S. Capitol, engaging in in-depth discussions with U.S. lawmakers to drive the implementation of blockchain technology policies.",
  "card4Title":"Top-Tier Global Investment Support",
  "card4Desc":"CESS has secured strong backing from top investment institutions, including DWF Labs, HTX Ventures, IVC (Infinity Ventures Crypto), Web3 Foundation, and more, assisting its expansion into global markets.",
  "card5Title":"Strategic Partnerships",
  "card5Desc":"CESS has established deep collaborations with industry leaders and organizations such as IEEE, GBA, Intel, Tencent, AWS, Bitcoin Cash, Polkadot, 42DAO, DPIN, IoTex, and others, working together to drive innovation and application of decentralized storage technology.",
  "table1Title":" Node License",
  "table1Desc":"The CESS Pathfinder node license is an ERC721 NFT. Holders can earn rewards by running the Pathfinder node client. The node client can be operated on personal machines, VPS, or NAS, or delegated to other users' machines.",
  "table2Title":" Token Distribution and Reward Mechanism",
  "table2Desc":"The total supply of $CESS tokens is 10 billion, with 65% (6.5 billion) allocated as node rewards. In the first year, approximately 1.018 billion tokens will be distributed as rewards to node providers. Afterward, the rewards will be halved every four years to ensure the sustainability of the long-term incentive mechanism.",
  "table2Desc2":"The total number of CESS Pathfinder nodes is 35,000. Currently, stages 1 to 4 have all been sold out, with the details as follows:",
  "table3Title":" Node Yield Estimate",
  "table3Title2":"First-Year Earnings Projection",
  "table4Title":"Second Year to nth Year Earnings Estimate",
  "table4Desc":"Starting from the second year, the Pathfinder node NFT will be able to bind to hardware for participation in global mining. Each node NFT represents 1T of staked coin computing power, generating corresponding mining rewards.",
  "table4Desc1":"*Starting from the third year, earnings will decrease by 15.9% annually.",
  "des1":"CESS and DPIN have officially established a global strategic partnership, working together to drive innovative breakthroughs in the DePIN and AI fields, and co-create a future ecosystem for decentralized GPU computing power and high-performance computing.",
  "des2":"Within this collaboration framework, DPIN's computing power relies on CESS's decentralized storage services, while CESS provides strong AI GPU computing infrastructure support to DPIN, promoting synergistic development in the storage and computing sectors.",
  "des3":"To enable more users to participate in this revolutionary ecosystem, the CESS Pathfinder Node subscription channel is now open. Each node is priced at ",
  "des3_af":" USDT tokens. Users can directly join this cutting-edge blockchain storage ecosystem through DPIN tokens, witnessing technological breakthroughs and innovation together.",
 "node_gou":"Node Subscription",
  "node_gou_price":"Node Subscription Price",
  "node_leave":"Nodes Remaining",
  "node_total":"Total Price",  
  "OperationFailed":"Operation Failed",
  "depin_not_enough":"DPIN balance is insufficient",
  "usdt_not_enough":"USDT balance is insufficient",
  "buy_node_success":"Purchase successful, waiting for block confirmation",
  "Alreadysubscribed":"Already subscribed",
  "neterror":"Network error, please refresh and retry",

  "ConferenceDetails":"Conference Details",
  "ConferenceTime":"Conference Date: March 8, 2025",
  "ConferenceLocation":"Conference Venue: Regal Skycity Hotel, Hong Kong",
  "ConferenceParticipants":"Attendance limit: Registration closes once 500 spots are filled.",
  "ConferenceRegistrationDate":"Registration deadline: March 5, 2025.",
  "ConferenceFee":"Conference Fee",
  "ConferenceRegistration":"Attendees are required to pay ",
  "ConferenceRegistration_af":" DPIN tokens",
  "EligibilityRegistrationFee":"Eligibility for Waiver of Registration Fee",
  "EligibilityRegistrationFeeDesc":"New and existing users who participate in staking after February 1, 2025, can enjoy one registration fee waiver opportunity for every 2000 USDT staked!",
  "DPINprovides":"DPIN Foundation provides",
  "DPINprovidesDesc":"Hotel accommodation and dinner arrangements for March 8th",
  "DPINprovidesDesc_af":"",
  "RegistrationInformation":'Registration Information',
  "passportName":"Passport Name (as per passport)",
  "Enterpassportname":"Enter passport name",
  "Gender":"Gender",
  "EnterGender":"Select your gender",
  "passportNumber":"Passport Number",
  "Enterpassportnumber":"Enter passport number",
  "PhoneNumber":"Contact Phone",
  "EnterPhoneNumber":"Enter your phone number",
  "freeadmission":"Congratulations! You have one free admission spot.",
  "Submitnow":"Submit now",
  "GenderMale":"Male",
  "GenderFemale":"Female",
  "Pleasefillinallinformation":"Please fill in all information",
  "Congratulations":"Congratulations! You have ",
  "Confirmation":"Confirm",
  "ConfirmationMessage":"Please confirm that the information you have filled in is correct. Once submitted, it cannot be changed. Are you sure you want to submit your registration information?",
  "FreeNum":" free admission spots.",
  "SubmitSuccess":"Submit successfully",
  "SubmitFail":"Submit failed",

  "form1Desc":"In 2024, DPIN successfully held a series of industry consensus meetings in various countries and regions, including Bangkok, Thailand, Malacca, Malaysia, and Singapore. As we move into 2025, DPIN will continue to promote the implementation of its business model and is committed to building the world's largest decentralized GPU computing power network.",
  "form2Desc":"On March 8, 2025, the 2025 Global DPIN Launch Summit & AI+DePIN Summit / Hong Kong / will be grandly held in Hong Kong, marking an important milestone for the global AI+DePIN industry. This summit will gather top experts, developers, entrepreneurs, and investors from around the world to jointly promote the deep integration of Web3 with the real world and open a new chapter in the digital economy.",
  "form3Desc":"The summit will deeply explore how AI and DePIN technologies can drive DPIN to become the global leader in GPU computing power networks, helping the industry move towards a more mature and innovative future.",
  "form4Desc":"One of the core goals of this summit is to build a bridge between DPIN and the global capital markets, promote its large-scale development, accelerate the global adoption of DePIN technology, and focus on constructing the world's largest GPU computing power network to drive the implementation and commercialization of the DPIN ecosystem.",
  "ticketPrice":"Ticket Price",
  "tipForm":"Friendly reminder: Conference badges will be distributed upon registration. All attendees are required to present their badges for entry and exit at the venue.",
  "RegistrationDetails":"Registration Details",
  "success":"Success",
  "fail":"Fail",
  "pending":"Pending",
  "FREE":"FREE",
  "FreeTitle": "1.Free Registration Eligibility",
  "StandardTitle": "2.Standard Conference Fee",
  "SpecialTitle": "Special Benefit：Pay 100 DPIN tokens and receive an additional free conference pass!",
  "timeout":"Network request timeout, please try again later.",
  "withdrawable_amount": "Withdrawable Amount",
  "withdraw_amount": "Amount to Withdraw",
  "enter_withdraw_amount": "Enter Amount",
  "all": "All",
  "ecological_construction": "Ecosystem Development",
  "ecological_pool_amount": "Ecological Pool Amount ",
  "ecological_pool_tip": "When the Ecosystem Fund reaches 300 BLC, one CESS node will be automatically purchased.",
  "amount_received": "Received Amount: ",
  "time_machine": "42Force Dashboard",
  "AirportDetails": "Airdrop Details",
  "Details": "Ecological Pool Details",
  "issued_amount": " Total Supply",
  "circulating_amount": "Circulation",
  "destroyed_amount": "Burned Amount",
  "total_computing_power": "Network Node Power",
  "yesterday_airdrop": "Yesterday's Airdrop",
  "my_computing_power": "My Node Power",
  "max_computing_power": "Max Node Power",
  "computing_power_accelerating": "Valid Node – In Acceleration.",
  "invalid_node_tip": "Node Invalid – Acceleration Unavailable",
  "invalid_Value": "Inactive node, unable to gain node Power acceleration",
  "hold_ftd_requirement": "Hold at least 0.42 FTD.",
  "hold_blc_requirement": "Hold at least one node with ≥ 420BLC.",
  "node_subscription": "Node Subscription",
  "remaining_nodes": "Remaining Nodes",
  "insufficient_balance_current": "Insufficient balance, current balance is",
  "authorize": "Authorize",
  "confirm": "Confirm",
  "subscription_range": "Subscription range is 14-20,000 BLC",
  "blc_authorization": "BLC Authorization",
  "force_alliance": "Built by 42Force Alliance",
  "super_node_reward_pool": "REWARD POOL",
  "coming_soon": "Coming Soon",
  "airdrop": "Airdrop",
  "fc_balance": "FC Balance",
  "fc": "FC",
  "SuperCommunity": "Super Community",
  "airdrop_pool": "Airdrop Pool",
  "airdrop_pool_tip": "Airdrop Pool Tip",
  "purchased_nodes": "Subscribed Nodes",
  "subscribe": "Subscribe",
  "withdraw": "Withdrawal",
  "blc": "BLC",
  "FC": "FC",
  "blc_mint_exchange": "BLC Minting",
  "swap_exchange": "42DAO Swap",
  "burn_pool": "Burn Pool",
  "insufficient_balance_current_blc": "Insufficient BLC Balance",
  "insufficient_balance_current_ftd": "Insufficient FTD Balance",
  "insufficient_balance_current_fc": "Insufficient FC Balance",
  "subscription_Tip": "Each account can only subscribe once",
  "InviteRecord": "My Invitations",
  "confirming_block": "Confirming Block",
  "withdraw_amount_error": "Withdrawal amount must be greater than ",
  "PleaseEnter":"Please Enter",
  "NodeHigher":"Node consensus must be equal to or higher than previous levels.",
  "subscribeOnce":"You can only subscribe to one node per settlement cycle.",
  "CongratulationsSign":"Congratulations!",
  "earned":"You've earned a ",
  "power_bonus":"power bonus.",
  "SmartRiskControlPool":"Smart Risk Control Pool",
  "accelerate_address":"Acceleration Address",
  "PaymentToken":"Payment Token",

  "IgnitionProgram":"Ignition Program",
  "Dashboard":"Dashboard",
  "TotalValidNodeExpansion":"Total Valid Node Expansion",
  "TotalAirdropReward":"Total Airdrop Reward",
  "ActivityTime":"Starting May 1, 2025 (UTC+8), Phase 1 runs for one month.",
  "RewardRules":"Reward Rules",
  "Notice":"Important Notes",
  "RewardDetails":"Reward Distribution",
  "RewardRulesDesc1":"Initiate participation of <span>3</span> valid nodes to receive <span>0.42</span> FC.",
  "RewardRulesDesc2":"Initiate participation of <span>10</span> valid nodes to receive an additional <span>0.42</span> FC.",
  "RewardRulesDesc3":"Each node can receive up to <span>1.68</span> FC in airdrop rewards.",
  "RewardRulesDesc4":"Newly initiated nodes must complete their first valid node subscription to qualify for activity statistics.",
  "RewardRulesDesc5":"Re-subscriptions of existing valid nodes are excluded from activity statistics.",
  "RewardRulesDesc6":"Airdrop rewards are sourced from community operations funds under the DAO governance framework and are automatically distributed via smart contract mechanisms through the Super Node reward pool.",

  "quick_entry":"Quick Access",
  "FateRoad":"Dashboard",
  "PurchasedNodes":"Purchased Nodes",
  "BecomeDonor":"Become A Donor",
  "InventoryNodes":"Inventory Nodes",
  "TransferRecord":"Transfer History",
  "open":"Activate",
  "Transfer":"Transfer",
  "confirm_open":"Are you sure you want to activate this node?",
  "TransferAddress":"Transfer Address",
  "PleaseEnterTransferAddress":"Please Enter Address",
  "TransferSuccess":"Transfer Success",
  "Donor":"Donor",
  "PaymentAmount":"Payment Amount",
  "PurchaseAmount":"Purchase Amount",
  "PurchasedAmount":"Purchased Amount",
  "PledgeCycle":"Pledge Cycle",
  "PledgeAmount":"Pledge Amount",
  "PledgeCycleDesc":"3 months",
  "PledgeAmountDesc":"Pledge FC value range is",
  "PledgeRecord":"Pledge Record",
  "PledgeTime":"Pledge Time",
  "PledgeEndTime":"Expiry Time",
  "Pledgeing":"Staking",
  "PledgeEnd":"Expired",
  "PledgeConfirming":"Confirming Redemption",
  "DonorAmount":"Donor Quota",
  "DonorAmountNotEnough":"Insufficient Donor Quota",
  "Pledge":"Pledge",
  "staking_success":"Staking Success",
  "staking_fail":"Staking Failed",
  "transfer_from":"Transfer From",
  "base_computing_power":"Base Power",
  "compensation_computing_power":"Accelerated Power",

  "super_community": "Super Community",
  "super_community_rules": "Super Community Rules",
  "badge": "Badge",
  "badge_num": "Badge Quantity >",
  "destroy_fc_get_badge": "Destroy FC to get badge",
  "bonus_income": "Bonus Income:",
  "destroy": "Destroy",
  "badge_global": "Global Badge",
  "badge_country": "Country Badge",
  "badge_continent": "Continent Badge",
  "merge": "Merge",
  "merge_tip": "Tip",
  "merge_confirm": "Are you sure to use 7 different {type} badges to exchange for 1 {target} badge?",
  "cancel": "Cancel",
  "badge_country_list": {
    "1": "India",
    "2": "France",
    "3": "SA",
    "4": "USA",
    "5": "Brazil",
    "6": "NZ",
    "7": "Antarctica(INT)"
  },
  "badge_continent_list": {
    "8": "Asia",
    "9": "Europe",
    "10": "Africa",
    "11": "NA",
    "12": "SA",
    "13": "Oceania",
    "14": "Antarctica"
  },
  "destroy_action": "Destroy",
  "approve_action": "Approve",
  "destroy_fc_get": "Destroy FC to get {type} badge",
  "get_badge_num": "Number of badges obtained:",
  "destroy_fc_num": "Number of FC destroyed:",
  "destroy_success": "Congratulations",
  "get_one_badge": "You got 1 {type} badge",
  "badge_type_country": "Country",
  "badge_type_continent": "Continent",
  "badge_type_global": "Global",
  "destroy_record": "Destroy Record",
  "no_content": "No content",
  "no_more": "No more",
  // Rules dialog
  "rules_intro": "Super Community: Country Badge, Continent Badge, and Global Badge",
  "rules_upgrade_way": "Upgrade way: Septenary merge upgrade",
  "rules_upgrade_rule": "Upgrade rules:",
  "rules_country_badge": "Country Badge",
  "rules_continent_badge": "Continent Badge",
  "rules_global_badge": "Global Badge",
  "rules_detail_1": "Destroy 7 FC to randomly get a country community badge",
  "rules_detail_2": "Collect 7 different country community badges + destroy 7 FC to get a continent community badge",
  "rules_detail_3": "Collect 7 different continent community badges + destroy 70 FC to get a global community badge",
  "rules_reward": "Reward starts: When continent communities reach 42 and global communities reach 10, the super community reward is activated.",
  "transfer_badge": "Transfer Badge",
  "no_badge": "No Badge",
  "transfer_address": "Transfer Address",
  "transfer_num": "Transfer Quantity",
  "confirm_transfer": "Confirm",
  "country_badge": "Country Badge",
  "continent_badge": "Continent Badge",
  "PleaseEnterTransfer": "Please Enter Transfer Address",
  "transfer_success": "Transfer Success",
  "transfer": "Transfer",
  "transfer_record": "Transfer Record",
  "destroySuccess": "Destroy Success, waiting for block confirmation",
  // supernode 多语言
  "supernode_rules_title": "Super Node Rules",
  "supernode_rules_incentive_governance": "Incentive Governance",
  "supernode_rules_start_condition": "Start Condition: Pool FC ≥ 20,000.",
  "supernode_rules_incentive_qualification": "Incentive Qualification: Destroy 50 FC.",
  "supernode_rules_daily_airdrop": "Daily Airdrop: Weighted distribution by contribution value.",
  "supernode_rules_contribution_acquire": "How to Get Contribution Value",
  "supernode_rules_main_community": "Main Community: 100 valid nodes = 1 contribution value, each additional 100 valid nodes = 0.2 contribution value (no upper limit).",
  "supernode_rules_sub_community": "Sub Community: Every 100 valid nodes = 1 contribution value (max 7), 700 valid nodes upgrade to super node and +7 contribution value.",
  "supernode_rules_governance": " Governance",
  "supernode_rules_dao_desc": "The global promotion of the 42FORCE Alliance will hold offline node consensus activities. The cost plan is initially reviewed and reported by the super node, and major activities are decided by super node voting.",
  "supernode_title": "Super Node",
  "supernode_community_contribution": "Community Contribution Value",
  "supernode_main_community": "Main Community",
  "supernode_sub_community": "Sub Community",
  "supernode_bonus_status": "Bonus Status",
  "supernode_contribution_value": "Contribution Value",
  "supernode_get_bonus_qualification": "Get Bonus Qualification",
  "supernode_already_got": "Already Got",
  "supernode_need_destroy": "Need Destroy",
  "supernode_bonus_income": "Bonus Income",
  "supernode_destroy": "Destroy",
  "supernode_authorize": "Authorize",
  "supernode_destroy_record": "Destroy Record",
  "supernode_pending_confirm": "Pending Confirmation",
  "supernode_got_bonus_qualification": "Got Bonus Qualification",
  "supernode_accelerate_address": "Accelerate Address",
  "supernode_no_content": "No Content",
  "supernode_loading": "Loading...",
  "performance": "Performance",
  "performance_day": "Daily Increase",
  "performance_week": "Weekly Increase",
  "performance_month": "Monthly Increase",
  "performance_total": "Total Increase",
}

export default en
