const tw = {
  "loading":"加載中...",
  "widraw-fee":"提幣手續費",
  "amount":"金額",
  "Trans-Fee": "手續費",
  "withdrawal-scuu": "提幣成功",
  "tip":"提示",
  "Exit":"登出",
  "Ok":"確定",
  "OK1":"確認",
  "Amount":"數量",
  "InviteWallAddre":"邀請錢包地址",
  "EnterInviteWallAddre":"請輸入邀請錢包地址",
  "Rewardratio":"獎勵比例",
  "DodeleteDode":"是否刪除此超級節點?",
  "SuperSettings":"超級節點設置",
  "SuperNode":"超級節點",
  "ConnectWallet":"連接錢包",
  "connectyourwallet":"請先連接錢包",
  "okchian":"請選擇正確的主鏈",
  "Balance":"餘額",
  "superList":'超級節點列表',
  "Super":"超级",
  "Withdrawtowallet":"提幣到錢包",
  "Stake":"訂閱",
  "StakeTime":"訂閱時間",
  "Two-Week":"二周",
  "Three-Week":"三周",
  "Four-Week":"四周",
  "Flexible":"靈活",
  "Mypledge":"我的質押",
  "CurrentStaking":"當前質押",
  "StakingInProcess":"購買中",
  "StakEd":"已到期",
  "FlexibleStaking":"靈活質押",
  "Minted":"已空投",
  "StakingPeriod":"質押時間",
  "ExpiryTime":"到期時間",
  "Redeem":"贖回",
  "NoMore":"沒有更多了",
  "Redeeming":"赎回中...",
  "copied":"復製成功",
  "Restake":"再次質押",
  "NoStake":"當前無質押",
  "Participate":"我要推廣",
  "Users":"用戶",
  "Node":"節點",
  "Settings":"設置",
  "SettingsFull":"設置成功",
  "NumberUsers":"邀请數量",
  "TotalNodeAmount":"節點總質押量",
  "SuperTotalNodeAmount":"超級節點總質押量",
  "TotalEarningsFTD":"節點FTD總收益",
  "SuperTotalEarningsFTD":"超級節點FTD總收益",
  "JoinDot":"請先加入節點",
  "InvitationLink":"邀請地址",
  "InvitationAddress":"邀請錢包地址",
  "Cancel":"取消",
  "Copylink":"複製地址",
  "surestake":"您確定要贖回此筆質押嗎？",
  "RedeemSuccessful":"贖回成功",
  "InsufficientBLCbalance":"BLC余额不足",
  "InsufficientFTDbalance":"FTD余额不足",
  "Authorization":"授權中...",
  "Authorizationsuccessful":"授權成功",
  "AuthorizationFail":"授權失敗",
  "AuthorizationTo":"授權",
  "Confirm":"確認",
  "Two-WeekSuccessful":"兩周質押成功",
  "ID":"編號：",
  "InvitedUsers":"已邀請用戶",
  "ActiveUsers":"有效用戶",
  "WalletAddress":"錢包地址",
  "EnterWalletAddress":"請輸入錢包地址",
  "RegistrationDate":"註冊時間",
  "NoContent":"暫無數據",
  "TotalStakingAmount":"總質押量",
  "NumberofUsers":"用戶數量",
  "TotalFTDMinted":"超級節點獎勵",
  "NodeReward":"節點質押獎勵",
  "Annualpledge":"年質押",
  "Price":"價格：",
  "NodeUnlocked":"節點已解鎖",
  "AtLeast":"至少 ",
  "Withdraw":"提幣",
  "TransactionFee":"手續費：",
  "WithdrawSuccessful":"提幣成功",
  "StakeSuccessful":"訂閱成功",
  "StakeFailed":"訂閱失敗",
  "totalStake":"總質押量",
  "details":"明細",
  "Withhold30%":"提幣扣除30%手續費作為算力投資",
  "Withdrawalquantity":"可提幣數量",
  "ConfirmingBlock":"區塊確認中",
  "pricerepledge":"價格已更新，請重新質押",
  "ConnectBNBChain":"以BNB Chain連接",
  "AddressFormatError": "錢包地址格式錯誤",
  "Staking":"質押中",
  "Expired":"已到期",
  "ConfirmingRedemption":"贖回確認中",
  "Redeemed":"已贖回",
  "DataStatistics":"數據統計截至",
  "loadig":"加載中...",
  "SystemMaintenance":"系統正在維護中，請稍後再試。",
  "desNo3000":"累計總抵押價值不能超過3000USDT",
  "CurrentHoldings":"當前鎖定",
  "TotalHoldings":"總鎖定",
  "WithdrawAmount":"提幣數量",
  "PowerAllocation":"算力配置",
  "pledgeYear":"質押週期為1年",
  "areYouOut":"你確定要登出",
  "mei":"麼?",
  "SuperAirdrop":"超級節點社區空投",
  "SuperAirdrop1":"超級節點社區空投",
  "totalSuperAirdrop":"超級節點社區總空投量",
  "NodeAirdrop":"節點社區空投",
  "totalNodeAirdrop":"節點社區總空投量",
  "Quantityreceived":"到賬數量",
  "deleteSucc":"删除成功",
  "WalletBalance":"錢包餘額",
  "APR":"APR：",
  "released": "已釋放餘額",
  "airdropped": "已空投餘額",
  "burned": "已銷毀",
  "available": "可用餘額",
  "withdrawable": "可提幣餘額",
  "staging_balance": "可分期釋放餘額",
  "burn_info": "銷毀比例 / 釋放速度 / 銷毀數量",
  "release_action": "釋放",
  "release_Amount":"釋放數量",
  "release_empty": "釋放數量不能為空",
  "burn_pool_balance": "銷毀池內可用餘額",
  "burn_pool_insufficient": "銷毀池內可用餘額不足",
  "burn": "去銷毀",
  "Burn":"銷毀",
  "pool": "銷毀池",
  "pending_release": "待釋放餘額",
  "days":"天",
  "sureBurn":"你確定要銷毀麼?",
  "enterQuantity":"銷毀數量必須大於0",
  "Operationsuccessful":"操作成功",
  "Insufficientrelease":"可分期釋放餘額不足",
  "TransactionCancelled":"交易取消",
  "Insufficien":"餘額不足",
  "All":"全部",
  "Insufficientwithdrawal":"可提现餘額不足",
  "Insufficientreleased":"已释放餘額不足",
  "Signatureinprogress":"簽名中...",

  "nodeSub":"節點認購",
  "nodeSubTitle":"背景介紹",
  "desMain":"CESS致力於打造基於區塊鏈的分散式雲端儲存系統，採用先進的虛擬化技術高效管理全球儲存資源，致力於為全球用戶提供一致且高效的分散式儲存服務。目前，CESS Pathfinder節點正在發售中，",
  "desMain1":"個節點中已有",
  "desMain2":"個售罄，剩餘",
  "desMain3":"個節點，機會難得。",
  "card1Title":"產業領先地位",
  "card1Desc":"CESS首創IEEE去中心化儲存協議標準，為全球範圍的應用奠定堅實基礎，推動產業標準化進程。",
  "card2Title":"全球市場與政府資源",
  "card2Desc":"CESS是GBA和BA的重要成員，並引領GBA亞洲分會，積極推動全球去中心化儲存的普及與發展。",
  "card3Title":"政策推動與產業對話",
  "card3Desc":"CESS受邀參加美國國會山莊的DePIN Fly-In簡報會，與美國立法者展開深入對話，推動區塊鏈技術政策的落地與實施。",
  "card4Title":"全球頂級投資支持",
  "card4Desc":"CESS獲得了頂級投資機構的強力支持，包括DWF Labs、HTX Ventures、IVC (Infinity Ventures Crypto)、Web3 Foundation等，協助其在全球市場的擴展。",
  "card5Title":"戰略合作夥伴",
  "card5Desc":"CESS與產業領導者和組織建立深度合作關係，包括IEEE、GBA、Intel、騰訊、AWS、Bitcoin Cash、Polkadot、42DAO、DPIN、IoTex等，共同推動去中心化儲存技術的創新與應用。",
  "table1Title":"節點許可證",
  "table1Desc":"CESS Pathfinder節點授權為ERC721 NFT，持有者可透過執行Pathfinder節點用戶端獲得獎勵。節點客戶端可以在個人機器、VPS或NAS上運行，或委託給其他使用者的機器。",
  "table2Title":"代幣分配與獎勵機制",
  "table2Desc":"CESS Pathfinder節點授權為ERC721 NFT，持有者可透過執行Pathfinder節點用戶端獲得獎勵。節點客戶端可以在個人機器、VPS或NAS上運行，或委託給其他使用者的機器。",
  "table2Desc2":"CESS Pathfinder節點總數為35000個，目前第1-4階段已經全部售罄，具體情況如下：",
  "table3Title":"節點收益率預估",
  "table3Title2":"第一年收益推算",
  "table4Title":"第二年至第n年收益預估",
  "table4Desc":"從第二年起，Pathfinder節點的NFT將可綁定硬件，參與全網挖礦。每個節點NFT代表1T的質押幣算力，帶來相應的挖礦收益。",
  "table4Desc1":"*從第三年起，收益每年減少15.9%",
  "des1":"CESS與DPIN正式建立全球策略夥伴關係，攜手推動DePIN與AI領域的創新突破，共同建構去中心化GPU算力與高效能運算的未來生態體系。",
  "des2":"在這一合作框架下，DPIN的算力依託於CESS的去中心化存儲服務，同時為CESS提供強大的AI GPU算力基礎設施支持，推動雙方在存儲和計算領域的協同發展。",
  "des3":"為了讓更多用戶參與這一革命性生態，CESS Pathfinder Node的認購通道現已開啟。每個節點的認購價格為",
  "des3_af":"USDT代幣，用戶可以通過DPIN代幣直接加入這一前沿的區塊鏈存儲生態系統，共同見證技術的突破與創新。",
  "node_gou":"節點認購",
  "node_gou_price":"節點認購價格",
  "node_leave":"節點剩餘",
  "node_total":"總價",
  "OperationFailed":"操作失敗",
  "depin_not_enough":"DPIN餘額不足",
  "usdt_not_enough":"USDT餘額不足",
  "buy_node_success":"購買成功,等待區塊確認",
  "Alreadysubscribed":"已認購",
  "neterror":"網絡錯誤，請重繪重試",
  "ConferenceDetails":"會議詳情",
  "ConferenceTime":"會議時間：2025年3月8日；",
  "ConferenceLocation":"會議地點：香港麗豪航天城酒店；",
  "ConferenceParticipants":"參會人數：報名額滿500人為止；",
  "ConferenceRegistrationDate":"報名截至時間：2025年3月5日；",
  "ConferenceFee":"會議費用",
  "ConferenceRegistration":"參會人員需支付",
  "ConferenceRegistration_af":"DPIN代幣",
  "EligibilityRegistrationFee":"免報名費資格",
  "EligibilityRegistrationFeeDesc":"2025年2月1日之後參與質押的新老用戶，每質押價值 2000 USDT可享一次報名費減免。",
  "DPINprovides":"DPIN基金會提供",
  "DPINprovidesDesc":"3月8日的酒店住宿及晚宴安排",
  "DPINprovidesDesc_af":"",
  "RegistrationInformation":'報名資訊',
  "passportName":"護照姓名（與護照一致）",
  "Enterpassportname":"請輸入護照姓名",
  "Gender":"性別",
  "EnterGender":"選擇您的性別",
  "passportNumber":"護照號碼",
  "Enterpassportnumber":"請輸入護照號碼",
  "PhoneNumber":"聯繫電話",
  "EnterPhoneNumber":"請輸入您的電話",
  "freeadmission":"恭喜！您擁有1個免費參會名額。",
  "Submitnow":"立即提交",
  "GenderMale":"男",
  "GenderFemale":"女",
  "Pleasefillinallinformation":"請填寫完整信息",
  "Confirmation":"確認",
  "ConfirmationMessage":"請確認填寫信息是否正確，提交後不可更改，您確定要提交報名信息嗎？",
  "Congratulations":"恭喜！您擁有",
  "FreeNum":"個免費參會名額。",
  "SubmitSuccess":"報名成功",
  "SubmitFail":"報名失敗",
  "form1Desc":"2024年，DPIN在泰國曼谷、馬來西亞馬六甲、新加坡等多個國家和地區成功舉辦了一系列行業共識會議。進入2025年，DPIN將持續推動其商業模式的落地，並致力於構建全球最大的去中心化GPU算力網絡。",
  "form2Desc":"2025年3月8日，2025全球DPIN啟動峰會暨AI+DePIN高峰論壇 /Hong Kong/ 將在香港隆重舉行，成為全球AI+DePIN行業的重要里程碑。本次峰會將匯聚全球頂尖專家、開發者、企業家和投資人，共同推動Web3與現實世界的深度融合，開啟數字經濟的新篇章。",
  "form3Desc":"峰會將深入探討AI與DePIN技術如何推動DPIN成為全球領先的GPU算力網絡，助力行業邁向更加成熟與創新的未來。",
  "form4Desc":"本次峰會的核心目標之一是為DPIN與全球資本市場搭建橋樑，推動其規模化發展，加速DePIN技術的全球推廣，並致力於構建全球最大的GPU算力網絡，推動DPIN生態系統的落地與商業化應用。",
  "ticketPrice":"門票價格",
  "tipForm":"溫馨提示： 參會證將在報到時發放，請各位參會人員憑證進出會場。",
  "RegistrationDetails":"報名明細",
  "success":"成功",
  "fail":"失敗",
  "pending":"確認中",
  "FREE":"免費",
  "FreeTitle": "1、免費報名資格",
  "StandardTitle": "2、標準參會費用",
  "SpecialTitle": "特別福利：支付100 DPIN代幣，即可額外獲得一個免費參會名額！",
  "timeout": "網絡請求超時，請稍後再試",
  "airdrop": "空投",
  "fc_balance": "FC 餘額",
  "withdraw": "提幣",
  "purchased_nodes": "已購節點",
  "subscribe": "認購",
  "blc": "BLC",
  "x3": "X3",
  "subscribe_now": "立即認購",
  "super_node_reward_pool": "獎勵池",
  "coming_soon": "待開放",
  "fc": "FC",
  "SuperCommunity": "超級社區",
  "super_community_reward_pool": "獎勵池",
  "blc_mint_exchange": "BLC鑄造與兌換",
  "swap_exchange": "42DAO Swap交易所",
  "burn_pool": "銷毀池",
  "withdrawable_amount": "可提幣金額",
  "withdraw_amount": "提幣數量",
  "enter_withdraw_amount": "請輸入提幣數量",
  "all": "全部",
  "ecological_construction": "生態建設",
  "ecological_pool_amount": "生態建設池金額 ",
  "ecological_pool_tip": "生態建設池金額達到300BLC，將會自動購入CESS節點一個。",
  "amount_received": "到賬數量：",
  "time_machine": "42force發財道",
  "issued_amount": "發行量",
  "circulating_amount": "流通量",
  "destroyed_amount": "銷毀",
  "total_computing_power": "全網算力",
  "yesterday_airdrop": "昨日空投",
  "my_computing_power": "我的算力",
  "max_computing_power": "最大算力",
  "computing_power_accelerating": "有效節點算力加速中",
  "invalid_node_tip": "非有效節點,無法獲取算力加速",
  "hold_ftd_requirement": "持有至少0.42FTD",
  "hold_blc_requirement": "持有一個及以上的420BLC節點",
  "node_subscription": "節點認購",
  "remaining_nodes": "節點剩餘",
  "insufficient_balance_current": "餘額不足,當前餘額為",
  "authorize": "授權",
  "confirm": "確認",
  "subscription_range": "認購區間為 14-20000 BLC",
  "blc_authorization": "BLC 授權",
  "force_alliance": "42Force聯盟出品",
  "confirming_block": "區塊確認中",
  "subscribeOnce":"你只能在一個結算週期中訂閱一次節點",
  "PleaseEnter":"請輸入",
  "NodeHigher":"節點價格必須等於或高於前一級",
  "insufficient_balance_current_blc": "BLC餘額不足",
  "insufficient_balance_current_ftd": "FTD餘額不足",
  "insufficient_balance_current_fc": "FC餘額不足",
  "subscription_Tip": "每個帳戶只能訂閱一次",
  "InviteRecord": "我的邀請",
  "withdraw_amount_error": "提幣數量必須大於",
  "AirportDetails": "空投明細",
  "Details": "生態池明細",
  "CongratulationsSign":"恭喜!",
  "earned":"您擁有",
  "power_bonus":"算力獎勵",
  "SmartRiskControlPool":"智能風控池",
  "accelerate_address":"加速地址",
  "PaymentToken":"支付代幣",

  "IgnitionProgram":"星火計劃",
  "Dashboard":"計劃看板",
  "TotalValidNodeExpansion":"累計拓展有效節點",
  "TotalAirdropReward":"累計空投獎勵",
  "ActivityTime":"活動時間：2025年5月1日(UTC+8) 14:00時起，第一階段為期一個月",
  "RewardRules":"獎勵規則",
  "Notice":"注意事項",
  "RewardDetails":"獎勵發放",
  "RewardRulesDesc1":"成功拓展<span>3</span>個有效節點，獲<span>0.42</span>枚FC空投獎勵。",
  "RewardRulesDesc2":"成功拓展<span>10</span>個有效節點，再獲<span>0.42</span>枚FC空投獎勵。",
  "RewardRulesDesc3":"單節點最高可獲<span>1.68</span>枚FC空投獎勵。",
  "RewardRulesDesc4":"拓展的新節點完成首次有效節點認購，方符合活動統計條件。",
  "RewardRulesDesc5":"已成為有效節點的節點複投，不計入活動資料統計。",
  "RewardRulesDesc6":"空投獎勵從DAO治理框架下的社群運營資金中，通過智能合約機制，由超級節點獎勵池自動分配執行。",


  "quick_entry":"快捷入口",
  "FateRoad":"發財道",
  "PurchasedNodes":"已購節點",
  "BecomeDonor":"成為轉贈者",
  "InventoryNodes":"庫存節點",
  "TransferRecord":"轉送記錄",
  "open":"開啟",
  "Transfer":"轉送",
  "confirm_open":"您確認要開啟此節點麼？",
  "TransferAddress":"接收地址",
  "PleaseEnterTransferAddress":"請輸入接收地址",
  "TransferSuccess":"轉送成功",
  "Donor":"轉贈者",
  "PaymentAmount":"支付數量",
  "PurchaseAmount":"購買額度",
  "PurchasedAmount":"已購額度",
  "PledgeCycle":"質押週期",
  "PledgeAmount":"質押數量",
  "PledgeCycleDesc":"3個月",
  "PledgeAmountDesc":"質押FC價值區間為",
  "PledgeRecord":"質押記錄",
  "PledgeTime":"質押時間",
  "PledgeEndTime":"到期時間",
  "Pledgeing":"質押中",
  "PledgeEnd":"已到期",
  "PledgeConfirming":"區塊確認中",
  "DonorAmount":"轉贈者額度",
  "DonorAmountNotEnough":"轉贈者額度不足",
  "Pledge":"質押",
  "staking_success":"質押成功",
  "staking_fail":"質押失敗",
  "transfer_from":"轉送自",
  "base_computing_power":"基礎算力",
  "compensation_computing_power":"加速算力",

  "super_community": "超級社區",
  "super_community_rules": "超級社區規則",
  "badge": "徽章",
  "badge_num": "徽章數量 >",
  "destroy_fc_get_badge": "銷毀FC獲取徽章",
  "bonus_income": "分紅收益：",
  "destroy": "銷毀",
  "badge_global": "全球徽章",
  "badge_country": "國家徽章",
  "badge_continent": "大洲徽章",
  "merge": "合成",
  "merge_tip": "提示",
  "merge_confirm": "您確認使用7個不同的{type}徽章換取一個{target}徽章麼?",
  "cancel": "取消",
  "badge_country_list": {
    "1": "印度",
    "2": "法國",
    "3": "南非",
    "4": "美國",
    "5": "巴西",
    "6": "紐西蘭",
    "7": "國際南極"
  },
  "badge_continent_list": {
    "8": "亞洲",
    "9": "歐洲",
    "10": "非洲",
    "11": "北美洲",
    "12": "南美洲",
    "13": "大洋洲",
    "14": "南極洲"
  },
  "destroy_fc_get": "銷毀FC獲取{type}徽章",
  "get_badge_num": "獲得徽章的數量：",
  "destroy_fc_num": "銷毀FC的數量：",
  "destroy_action": "銷毀",
  "approve_action": "授權",
  "destroy_success": "恭喜您",
  "get_one_badge": "獲得1個{type}徽章",
  "badge_type_country": "國家",
  "badge_type_continent": "大洲",
  "badge_type_global": "全球",
  "destroy_record": "銷毀記錄",
  "no_content": "暫無內容",
  "no_more": "沒有更多了",
  "rules_intro": "超級社區：國家徽章、大洲徽章和全球徽章",
  "rules_upgrade_way": "進階方式：七進制聚合進階",
  "rules_upgrade_rule": "進階規則:",
  "rules_country_badge": "國家徽章",
  "rules_continent_badge": "大洲徽章",
  "rules_global_badge": "全球徽章",
  "rules_detail_1": "銷毀7枚FC隨機獲得一張國家社區徽章",
  "rules_detail_2": "集齊7張不同國家社區徽章+銷毀7枚FC得一張大洲社區徽章",
  "rules_detail_3": "集齊7張不同大洲社區徽章+銷毀70枚FC獲得一張全球社區徽章",
  "rules_reward": "獎勵啟動：當大洲社區達42個，全球社區達10個，開啟超級社區獎勵。",
  "transfer_badge": "轉贈徽章",
  "no_badge": "暫無徽章",
  "transfer_address": "轉贈地址",
  "transfer_num": "轉贈數量",
  "confirm_transfer": "確認",
  "country_badge": "國家徽章",
  "continent_badge": "大洲徽章",
  "PleaseEnterTransfer": "請輸入轉贈地址",
  "transfer_success": "轉贈成功",
  "transfer" : "轉贈",
  "transfer_record": "轉贈記錄",
  "destroySuccess": "銷毀成功,等待區塊確認",
  // supernode 多语言
  "supernode_rules_title": "超級節點規則",
  "supernode_rules_incentive_governance": "激勵治理",
  "supernode_rules_start_condition": "啟動條件：池內FC≥2萬枚。",
  "supernode_rules_incentive_qualification": "激勵資格：銷毀50枚FC。",
  "supernode_rules_daily_airdrop": "每日空投：按貢獻值加權分配。",
  "supernode_rules_contribution_acquire": "貢獻值獲取",
  "supernode_rules_main_community": "主社區：達100有效節點=1貢獻值，後續每+100有效節點=0.2貢獻值（無上限）。",
  "supernode_rules_sub_community": "從屬社區：每100有效節點=1貢獻值（上限7），達700有效節點升級超級節點並+7貢獻值。",
  "supernode_rules_governance": "治理",
  "supernode_rules_dao_desc": "42FORCE聯盟的全球推廣將舉辦線下節點共識活動，成本方案由超級節點初審上報，重大活動由超級節點投票決定。",
  "supernode_title": "超級節點",
  "supernode_community_contribution": "社區貢獻值",
  "supernode_main_community": "主社區",
  "supernode_sub_community": "從屬社區",
  "supernode_bonus_status": "分紅情況",
  "supernode_contribution_value": "貢獻值",
  "supernode_get_bonus_qualification": "獲得分紅資格",
  "supernode_already_got": "已獲得",
  "supernode_need_destroy": "需銷毀",
  "supernode_bonus_income": "分紅收益",
  "supernode_destroy": "銷毀",
  "supernode_authorize": "授權",
  "supernode_destroy_record": "銷毀記錄",
  "supernode_pending_confirm": "待確認",
  "supernode_got_bonus_qualification": "獲得分紅資格",
  "supernode_accelerate_address": "加速地址",
  "supernode_no_content": "暫無內容",
  "supernode_loading": "加載中...",
  "performance": "業績",
  "performance_day": "日新增",
  "performance_week": "周新增",
  "performance_month": "月新增",
"performance_total": "總新增",

  
  // =========================
  // view 目錄中文文案整理（新增）
  // =========================
  "head_tip_title": "產品中心溫馨提示",
  "head_tip_desc": "消耗 100 身份積分 完成數字身份鑄造，即刻開啟 DID 聯盟全系能力與服務。",
  "head_btn_go": "立即前往",
  "head_btn_get_points": "獲取身份積分",
  "head_menu_dashboard": "身份儀表盤",
  "head_menu_mint": "身份鑄造",
  "head_menu_product": "產品中心",
  "head_menu_trade": "交易中心",
  "head_menu_knowledge": "知識中心",

  "identity_title": "身份鑄造",
  "identity_power": "身份算力",
  "identity_points": "身份積分",
  "identity_power_reward": "身份算力獎勵",
  "identity_tab_mint": "身份鑄造",
  "identity_tab_gas": "GAS 支付",
  "identity_card_identity": "數字身份:",
  "identity_card_identity_desc": "完成 KYC 認證後，即可領取多國數字身份，並享受 DID 聯盟提供的多種數字服務。",
  "identity_card_power": "身份算力:",
  "identity_card_power_desc": "身份算力可以獲取DID獎勵，身份算力越多，獲取的獎勵越多。",
  "identity_card_points": "身份積分:",
  "identity_card_points_desc": "鑄造身份即可獲得身份積分，積分可兌換 DID 聯盟提供的數字身份權益或實體產品。",
  "identity_record_power": "身份算力記錄",
  "identity_record_power_reward": "身份算力獎勵記錄",

  "pledge_title": "DID質押",
  "pledge_personal": "個人質押",
  "pledge_weight": "質押權重",
  "pledge_weight_percent": "權重佔比",
  "pledge_reward": "質押獎勵",
  "pledge_action": "質押",
  "pledge_record_title": "質押獎勵記錄",
  "pledge_desc_1": "每次質押都會觸發收益分配。",
  "pledge_desc_2": "您的質押獎勵取決於三個因素：投入金額、質押時間、算力大小",
  "pledge_desc_3": "質押權重 = 個人算力 × 金額係數 × 時間係數",
  "pledge_desc_4": "金額係數：您的質押金額 ÷ 所有用戶質押金額中位數",
  "pledge_desc_5": "時間係數：您的質押週期 ÷ 所有用戶質押週期中位數",
  "pledge_desc_6": "每日獎勵：您的權重 ÷ 質押池權重 × 質押池獎勵",
  "pledge_desc_7": "質押獎勵 ： 質押池權重 / 全網質押池權重 * 全網質押池獎勵",

  "casting_title": "身份鑄造",
  "casting_tab_mint": "鑄造身份",
  "casting_tab_activate": "激活身份",
  "casting_section_mint": "鑄造身份",
  "casting_amount": "鑄造金額",
  "casting_quick": "快捷鑄造",
  "casting_pay_method": "支付方式",
  "casting_wallet_balance": "錢包餘額",
  "casting_redeem_code": "兌換碼",
  "casting_redeem": "兌換",
  "casting_record": "鑄造記錄",
  "casting_pending": "區塊鏈確認中",
  "casting_success": "鑄造成功",
  "casting_time": "鑄造時間:",
  "casting_input_hint": "*請輸入整百的數值",
  "casting_op_success": "操作成功",
  "casting_op_fail": "操作失敗",
  "casting_input_code": "請輸入兌換碼",

  "withdraw_title": "獎勵提現",
  "withdraw_all": "全部",
  "withdraw_arrival": "到賬數量",
  "withdraw_fee": "手續費:",
  "withdraw_action": "提現",
  "withdraw_record": "提現記錄",
  "withdraw_amount_gt_fee": "提現金額需大於手續費",
  "withdraw_success": "操作成功",

  "invite_title": "邀請記錄",
  "invite_my": "我的邀請",
  "invite_invited_users": "已邀請用戶",
  "invite_valid_users": "有效用戶",
  "invite_address_list": "地址列表",
  "invite_wallet_address": "錢包地址",  
  "invite_register_time": "註冊時間",
  "invite_identity_power": "身份算力",
  "invite_copied": "地址已複製",
  "invite_invite_me": "我要邀請",

  "pledge_form_title": "DID質押",
  "pledge_amount": "質押數量",
  "pledge_amount_placeholder": "請輸入數量",
  "pledge_all": "全部",
  "pledge_lock_time": "鎖倉時間",
  "pledge_lock_time_placeholder": "請輸入天數",
  "pledge_day": "天",
  "pledge_rate": "加倍速率:",
  "pledge_did_balance": "DID餘額:",
  "pledge_record": "質押記錄",
  "pledge_record_rate": "加倍速率:",
  "pledge_record_cycle": "鎖倉週期:",
  "pledge_record_start": "開始時間:",
  "pledge_record_end": "結束時間:",
  "pledge_redeem": "贖回",
  "pledge_insufficient_balance": "餘額不足",
  "pledge_authorize": "授權",
  "pledge_status_pending": "區塊確認中",
  "pledge_status_staking": "質押中",
  "pledge_status_expired": "已到期",
  "pledge_status_unknown": "未知狀態",
  "pledge_authorize_success": "授權成功",
  "pledge_authorize_fail": "授權失敗",
  "pledge_success": "質押成功",
  "pledge_fail": "操作失敗",
  "pledge_redeem_submitted": "贖回申請已提交",
  "pledge_get_records_fail": "獲取質押記錄失敗",
  
  // dashboard charts
  "dashboard_trend_title": "全網趨勢圖",
  "chart_identity_power": "全網身份算力",
  "chart_verification_contribution": "全網驗證貢獻",
  "chart_staking_weight": "全網質押權重",

  // gas page
  "gas_payment_title": "GAS費用支付",
  "expiring_power": "即將到期的算力",
  "remaining_payment_time": "剩餘支付時間",
  "activate_time_compensation_tip": "激活時間補償算力，提升收益",
  "fee_details": "費用明細",
  "identity_power_list": "身份算力列表",
  "select_all": "全選",
  "power_colon": "算力 ：",
  "original_identity_power": "原有身份算力",
  "time_power_compensation": "時間算力補償",
  "payment_ratio": "支付比例",
  "actual_payment_amount": "實際支付金額",
  "payment_method": "支付方式",
  "important_reminder": "重要提醒",
  "important_reminder_text": "個人算力超過 365 天未支付將清零。系統提供 7 天緩衝期，及時支付可激活最新時間算力補償。",
  "payment_authorize": "支付授權",
  "gas_tip_title_1": "為什麼需要支付Gas費用?",
  "gas_tip_content_1": "支付 Gas 費用用於維持身份算力池的持續運作及網絡算力維護，及時支付可在365天內保留算力，並激活最新時間算力補償。",
  "gas_tip_title_2": "支付比例計算公式",
  "gas_tip_content_2": "支付比例=鑄造數字身份的36.5%÷365×支付當天的天數。越早支付→支付比例低；越晚支付→支付比例高。<br>提前支付可及時激活時間算力補償，按支付當天算力增加個人算力值。",
  "gas_tip_title_3": "時間算力補償",
  "gas_tip_content_3": "時間算力補償=基礎算力×鑄造身份當天系統運行天數×0.1% <br>時間算力補償更新：<br>支付 Gas 費用後，系統會按支付當天計算時間補償算力，並自動更新您的算力，讓您獲得更高的個人算力值。",

  // valcontribution
  "val_title": "驗證貢獻",
  "val_detail_title": "驗證詳情",
  "val_contribution_data": "驗證貢獻數據",
  "val_personal_contribution": "個人驗證貢獻",
  "val_pool_contribution": "算力池驗證貢獻",
  "val_pool_reward": "算力池驗證貢獻獎勵",
  "val_record_title": "驗證貢獻記錄",
  "val_intro": "驗證者通過邀請更多身份加入 DID 網絡，提供驗證支持，穩固數字身份並維護網絡安全。貢獻越高，空投獎勵越豐厚，實現安全與激勵的正向循環。",
  "val_node_unlock": "節點釋放",
  "val_to_unlock_did": "待釋放 DID",
  "val_released_did": "已釋放 DID",
  "val_unlock_progress": "釋放進度",
  "val_unlock_tips": "註：新增個人驗證貢獻 100 ，解鎖1個DID",
  "val_personal_reward": "個人驗證貢獻獎勵",
  "val_recent_days_prefix": "註：驗證數據統計為近",
  "val_personal_bonus_reward": "個人驗證貢獻加成獎勵",
  "val_stat_from": "註：驗證數據統計為",
  "val_until_now": "至今",
  "val_node_unlock_record": "節點釋放記錄",
  "val_reward_record": "貢獻獎勵記錄",
  "val_bonus_reward_record": "加成獎勵記錄",
  "val_rule_title": "個人驗證貢獻獎勵規則",
  "val_rule_1": "個人新增驗證貢獻總和 = 全節點新增貢獻總額 — 最大節點新增貢獻。",
  "val_rule_2": "算力池驗證貢獻 = 近100天算力池新增驗證貢獻總和",
  "val_rule_3": "每日驗證貢獻獎勵 = （近100天個人新增驗證貢獻總和 ÷ 算力池驗證貢獻貢獻） × 每日算力池驗證貢獻獎勵",
}

export default tw;
