const Korea = {
    "loading": "로딩 중...",
    "widraw-fee": "출금 수수료",
    "amount": "금액",
    "Trans-Fee": "수수료",
    "withdrawal-scuu": "출금 성공",
    "tip": "알림",
    "Exit": "로그아웃",
    "Ok": "확인",
    "OK1": "확인",
    "Amount": "수량",
    "InviteWallAddre": "초대 지갑 주소",
    "EnterInviteWallAddre": "초대 지갑 주소를 입력하세요",
    "Rewardratio": "보상 비율",
    "DodeleteDode": "이 슈퍼 노드를 삭제하시겠습니까",
    "SuperSettings": "슈퍼 노드 설정",
    "SuperNode": "슈퍼 노드",   
    "ConnectWallet": "지갑 연결",
    "connectyourwallet": "먼저 지갑을 연결하세요",
    "okchian": "올바른 메인넷을 선택하세요",
    "Balance": "잔액",
    "superList": "슈퍼 노드 목록",
    "Super": "슈퍼",
    "Withdrawtowallet": "지갑으로 출금",
    "Stake": "담보",
    "StakeTime": "담보 시간",
    "Two-Week": "2주",
    "Three-Week": "3주",
    "Four-Week": "4주",
    "Flexible": "유연한 담보",
    "Mypledge": "내 담보",
    "CurrentStaking": "현재 담보",
    "StakingInProcess": "담보 중",
    "StakEd": "만료됨",
    "FlexibleStaking": "유연한 담보",
    "Minted": "에어드랍 완료",
    "StakingPeriod": "담보 시간",
    "ExpiryTime": "만료 시간",
    "Redeem": "상환",
    "NoMore": "더 이상 없습니다",
    "Redeeming": "상환 중...",
    "copied": "복사 완료",
    "Restake": "다시 담보",
    "NoStake": "현재 담보 없음",
    "Participate": "저는 홍보할 거예요",
    "Users": "사용자",
    "Node": "노드",
    "Settings": "설정",
    "SettingsFull": "설정 완료",
    "NumberUsers": "사용자 수",
    "TotalNodeAmount": "노드 총 담보량",
    "SuperTotalNodeAmount": "슈퍼 노드 총 담보량",
    "TotalEarningsFTD": "노드 FTD 총 수익",
    "SuperTotalEarningsFTD": "슈퍼 노드 FTD 총 수익",
    "JoinDot": "먼저 노드를 추가하세요",
    "InvitationLink": "초대 주소",
    "InvitationAddress": "초대 지갑 주소",
    "Cancel": "취소",
    "Copylink": "주소 복사",
    "surestake": "이 담보를 상환하시겠습니까?",
    "RedeemSuccessful": "상환 완료",
    "InsufficientBLCbalance": "BLC 잔액 부족",
    "InsufficientFTDbalance": "FTD 잔액 부족",
    "Authorization": "권한 부여 중...",
    "Authorizationsuccessful": "권한 부여 완료",
    "AuthorizationFail": "권한 부여 실패",
    "AuthorizationTo": "권한 부여",
    "Two-WeekSuccessful": "2주 담보 완료",
    "ID": "번호",
    "InvitedUsers": "초대한 사용자",
    "ActiveUsers": "유효 사용자",
    "WalletAddress": "지갑 주소",
    "EnterWalletAddress": "지갑 주소를 입력하세요",
    "RegistrationDate": "등록 시간",
    "NoContent": "현재 내용 없음",
    "TotalStakingAmount": "총 담보량",
    "NumberofUsers": "사용자 수량",
    "TotalFTDMinted": "슈퍼 노드 보상",
    "NodeReward": "노드 담보 보상",
    "Annualpledge": "연간 담보",
    "Price": "가격",
    "NodeUnlocked": "노드가 잠금 해제되었습니다",
    "AtLeast": "최소",
    "Withdraw": "출금",
    "TransactionFee": "수수료",
    "WithdrawSuccessful": "출금 성공",
    "StakeSuccessful": "담보 성공",
    "StakeFailed": "담보 실패",
    "totalStake": "총 담보량",
    "details": "명세",
    "Withhold30%": "출금 가능한 수량",
    "Withdrawalquantity": "출금 가능한 수량",
    "ConfirmingBlock": "블록 확인 중",
    "pricerepledge": "가격이 업데이트되었습니다. 다시 담보해 주세요.",
    "ConnectBNBChain": "BNB 체인으로 연결",
    "AddressFormatError": "지갑 주소 형식 오류",
    "Staking": "담보 중",
    "Expired": "만료됨",
    "ConfirmingRedemption": "상환 확인 중",
    "Redeemed": "상환 완료",
    "DataStatistics": "데이터 통계 기준",
    "loadig": "로딩 중...",
    "SystemMaintenance": "시스템이 유지보수 중입니다. 잠시 후에 다시 시도해 주세요.",
    "desNo3000": "누적 총 담보 가치가 3000USDT를 초과할 수 없습니다.",
    "CurrentHoldings": "현재 잠금",
    "TotalHoldings": "총 잠금",
    "WithdrawAmount": "출금 수량",
    "PowerAllocation": "담보 주기가 1년입니다",
    "pledgeYear": "담보 주기가 1년입니다",
    "areYouOut": "로그아웃 하시겠습니까?",
    "mei": "",
    "SuperAirdrop": "슈퍼 노드 커뮤니티 에어드롭",
    "SuperAirdrop1": "슈퍼 노드 커뮤니티 에어드롭",
    "totalSuperAirdrop": "슈퍼 노드 커뮤니티 총 에어드롭량",
    "NodeAirdrop": "노드 커뮤니티 에어드롭",
    "totalNodeAirdrop": "노드 커뮤니티 총 에어드롭량",
    "Quantityreceived": "입금 수량",
    "deleteSucc": "삭제 성공",
    "WalletBalance": "지갑 잔액",
    "APR": "APR：",
    "released": "해제된 잔액",
    "airdropped": "에어드롭된 잔액",
    "burned": "소각됨",
    "available": "사용 가능 잔액",
    "withdrawable": "출금 가능 잔액",
    "staging_balance": "분할 출금 가능 잔액",
    "burn_info": "소각 비율 / 해제 속도 / 소각 수량",
    "release_action": "해방",
    "release_Amount": "해방 수량",
    "release_empty": "해방 수량은 비워둘 수 없습니다",
    "burn_pool_balance": "소각 풀 내 사용 가능한 잉여 금액",
    "burn_pool_insufficient": "소각 풀 내 사용 가능한 잉여 금액이 부족합니다",
    "burn": "소각하기",
    "Burn": "소각",
    "pool": "소각 풀",
    "pending_release": "대기 해제 잔액",
    "days": "일",
    "sureBurn": "정말로 소각하시겠습니까?",
    "enterQuantity": "소각 수량은 0보다 커야 합니다",
    "Operationsuccessful": "작업 성공",
    "Insufficientrelease": "사용 가능한 잉여 금액 부족",
    "TransactionCancelled": "거래 취소",
    "Insufficien": "잔액이 부족합니다",
    "All":"전체",
    "Insufficientwithdrawal": "출금 가능 잔액 부족",
    "Insufficientreleased": "해제된 잔액 부족",
    "Signatureinprogress":"서명 중...",
    "OperationFailed":"작업 실패",
    "depin_not_enough":"DPIN 잔액이 부족합니다",
    "buy_node_success":"구매 성공, 블록 확인 대기 중",
    "timeout":"네트워크 요청 시간 초과, 잠시 후 다시 시도해 주세요.",
    "withdrawable_amount": "출금 가능 금액",
    "withdraw_amount": "출금 수량",
    "enter_withdraw_amount": "출금 수량을 입력하세요",
    "all": "전체",
    "ecological_construction": "생태계 구축",
    "ecological_pool_amount": "생태계 구축 풀 금액: ",
    "ecological_pool_tip": "생태계 구축 풀 금액이 300 BLC에 도달하면 CESS 노드 하나가 자동으로 구매됩니다.",
    "amount_received": "입금 수량: ",
    "time_machine": "42Force 타임머신",
    "issued_amount": "발행량",
    "circulating_amount": "유통량",
    "destroyed_amount": "소각",
    "total_computing_power": "전체 네트워크 컴퓨팅 파워",
    "yesterday_airdrop": "어제 에어드롭",
    "my_computing_power": "내 컴퓨팅 파워",
    "max_computing_power": "최대 컴퓨팅 파워",
    "computing_power_accelerating": "유효 노드 컴퓨팅 파워 가속 중",
    "invalid_node_tip": "유효하지 않은 노드, 컴퓨팅 파워 가속을 얻을 수 없습니다",
    "hold_ftd_requirement": "최소 0.42 FTD 보유",
    "hold_blc_requirement": "420BLC 노드 1개 이상 보유",
    "node_subscription": "노드 구독",
    "remaining_nodes": "남은 노드",
    "insufficient_balance_current": "잔액 부족, 현재 잔액은",
    "authorize": "승인",
    "confirm": "확인",
    "subscription_range": "구독 범위는 14-20000 BLC입니다",
    "blc_authorization": "BLC 승인",
    "force_alliance": "42Force 얼라이언스 제작",
    // "tipForm":"참가 증명서는 등록 시 발급됩니다. 모든 참가자는 참가 증명서를 제시하여 입장 및 퇴장할 수 있습니다."
};
export default Korea;
  